      - name: Build Kernel
        run: |
          chmod +x build_kernel.sh
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          export KBUILD_BUILD_USER="Admin102"
          export KBUILD_BUILD_HOST="Droidian-Builder"
          
          # إضافة خيارات لإهمال التحذيرات وتحويلها إلى مجرد تنبيهات وليس أخطاء
          export KCFLAGS="-Wno-error=strict-prototypes -Wno-error=format-zero-length -Wno-error=uninitialized"
          
          mkdir -p out
          # استخدام الـ Flag الخاص بتجاهل الأخطاء أثناء الـ make
          make O=out ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- KCFLAGS="$KCFLAGS" -j$(nproc)
          
          ./build_kernel.sh
          
